# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-04 12:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribers',
            options={'verbose_name': 'My subscriber', 'verbose_name_plural': 'A lot of subscribers'},
        ),
    ]
